version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.4'
    ports:
      - '9092:9092'
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
    depends_on:
      - zookeeper
  db:
    image: postgres:13
    restart: always
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: adminpostgres
      POSTGRES_PASSWORD: 87654321
      POSTGRES_DB: jojonomic

  # price-update-service:
  #   build:
  #     context: ../microservices/price-update-service/
  #   ports:
  #     - '8311:8000'
    
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  db:
    driver: local

networks:
  mynet:
    driver: bridge