## Build
FROM golang:1.21-alpine AS build

WORKDIR /app

COPY . /app

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/price-update-service

## Deploy
FROM alpine:3

WORKDIR /app
COPY .env /app
COPY --from=build /app/price-update-service /app

EXPOSE 8000

CMD ["/app/price-update-service"]
