## Build
FROM golang:1.21 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go mod tidy
RUN go build -o /app/price-update-service ./main.go
EXPOSE 8000
CMD /app/price-update-service

# ## Deploy
# FROM alpine:3

# WORKDIR /

# COPY --from=build /price-update-service /price-update-service

# EXPOSE 8000

# CMD ["/price-update-service"]
